### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'output/ner/dev1'

### ISSUE THREAD

**Issue by bangnguyen89** [pth1993/NNVLP#1]
When I run the bash file, there is one error as following

Training model...
Epoch 1 (learning rate=0.0100, decay rate=0.0500): 
train: 10/10 loss: 55.0562, acc: 10.14%, time: 1.09sestimated): 0.00s
Traceback (most recent call last):
  File "ner.py", line 226, in <module>
    alphabet_label, 'output/ner')
  File "/home/bang/NNVLP/network.py", line 211, in train_model
    is_flattened=False)
  File "/home/bang/NNVLP/utils.py", line 93, in output_predictions
    with open(filename, 'a') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'output/ner/dev1'

Could you please check and let me know the reason?
And how do you feed a word in your model?

Thank you

**Comment by bangnguyen89** [comment]
You can fix the above error by creating new folder output/ner inside NNVLP folder
